# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CE/DAKTMT/Vivado/project_dct/project_dct.srcs/sources_1/ip/ROM_COEFF/ROM_COEFF.xci
# IP: The module: 'ROM_COEFF' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/project_dct/project_dct.gen/sources_1/ip/ROM_COEFF/ROM_COEFF_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_COEFF'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CE/DAKTMT/Vivado/project_dct/project_dct.srcs/sources_1/ip/ROM_COEFF/ROM_COEFF.xci
# IP: The module: 'ROM_COEFF' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/project_dct/project_dct.gen/sources_1/ip/ROM_COEFF/ROM_COEFF_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_COEFF'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
