# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/TEST_BRAM/TEST_BRAM.xci
# IP: The module: 'TEST_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/TEST_BRAM/TEST_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TEST_BRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/TEST_BRAM/TEST_BRAM.xci
# IP: The module: 'TEST_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/TEST_BRAM/TEST_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TEST_BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
