# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/bd/kria_top/ip/kria_top_steganography_proces_0_3/kria_top_steganography_proces_0_3.xci
# IP: The module: 'kria_top_steganography_proces_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/u_sub_16/u_sub_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_sub_16 || ORIG_REF_NAME==u_sub_16} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/u_mult_16/u_mult_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_mult_16 || ORIG_REF_NAME==u_mult_16} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/u_add_16/u_add_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_add_16 || ORIG_REF_NAME==u_add_16} -quiet] -quiet

# XDC: d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_steganography_proces_0_3/kria_top_steganography_proces_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_top_steganography_proces_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/bd/kria_top/ip/kria_top_steganography_proces_0_3/kria_top_steganography_proces_0_3.xci
# IP: The module: 'kria_top_steganography_proces_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/u_sub_16/u_sub_16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_sub_16 || ORIG_REF_NAME==u_sub_16} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/u_mult_16/u_mult_16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_mult_16 || ORIG_REF_NAME==u_mult_16} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/u_add_16/u_add_16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_add_16 || ORIG_REF_NAME==u_add_16} -quiet] -quiet

# XDC: d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_steganography_proces_0_3/kria_top_steganography_proces_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_top_steganography_proces_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
