# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CE/DAKTMT/Vivado/datn_paper/datn_paper.srcs/sources_1/ip/u_mult_32/u_mult_32.xci
# IP: The module: 'u_mult_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/datn_paper/datn_paper.gen/sources_1/ip/u_mult_32/u_mult_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_mult_32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CE/DAKTMT/Vivado/datn_paper/datn_paper.srcs/sources_1/ip/u_mult_32/u_mult_32.xci
# IP: The module: 'u_mult_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/datn_paper/datn_paper.gen/sources_1/ip/u_mult_32/u_mult_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_mult_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
