# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/u_add_16/u_add_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_add_16 || ORIG_REF_NAME==u_add_16} -quiet] -quiet

# IP: ip/f_mult_32/f_mult_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_mult_32 || ORIG_REF_NAME==f_mult_32} -quiet] -quiet

# IP: ip/f_add_32/f_add_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_add_32 || ORIG_REF_NAME==f_add_32} -quiet] -quiet

# IP: ip/f_sub_32/f_sub_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_sub_32 || ORIG_REF_NAME==f_sub_32} -quiet] -quiet

# Block Designs: bd/kria_top/kria_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top || ORIG_REF_NAME==kria_top} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_zynq_ultra_ps_e_0_0/kria_top_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kria_top_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_cdma_0_0/kria_top_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_cdma_0_0 || ORIG_REF_NAME==kria_top_axi_cdma_0_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_xbar_0/kria_top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_xbar_0 || ORIG_REF_NAME==kria_top_xbar_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_ps8_0_axi_periph_0/kria_top_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_ps8_0_axi_periph_0 || ORIG_REF_NAME==kria_top_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_rst_ps8_0_99M_0/kria_top_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_rst_ps8_0_99M_0 || ORIG_REF_NAME==kria_top_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_smc_0/kria_top_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_smc_0 || ORIG_REF_NAME==kria_top_axi_smc_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_0_3/kria_top_axi_bram_ctrl_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_0_3 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_0_4/kria_top_axi_bram_ctrl_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_0_4 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_0_4} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_0_5/kria_top_axi_bram_ctrl_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_0_5 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_0_5} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_0_bram_2/kria_top_axi_bram_ctrl_0_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_0_bram_2 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_0_bram_2} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_1_bram_2/kria_top_axi_bram_ctrl_1_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_1_bram_2 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_1_bram_2} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_2_bram_1/kria_top_axi_bram_ctrl_2_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_2_bram_1 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_2_bram_1} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_bram_mux_0_0/kria_top_bram_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_bram_mux_0_0 || ORIG_REF_NAME==kria_top_bram_mux_0_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_bram_mux_1_0/kria_top_bram_mux_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_bram_mux_1_0 || ORIG_REF_NAME==kria_top_bram_mux_1_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_steganography_proces_0_3/kria_top_steganography_proces_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_steganography_proces_0_3 || ORIG_REF_NAME==kria_top_steganography_proces_0_3} -quiet] -quiet

# IP: ip/u_sub_16/u_sub_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_sub_16 || ORIG_REF_NAME==u_sub_16} -quiet] -quiet

# IP: ip/u_mult_16/u_mult_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_mult_16 || ORIG_REF_NAME==u_mult_16} -quiet] -quiet

# IP: ip/u_add_16/u_add_16.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==u_add_16 || ORIG_REF_NAME==u_add_16} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_bram_mux_0_1/kria_top_bram_mux_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_bram_mux_0_1 || ORIG_REF_NAME==kria_top_bram_mux_0_1} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_register_bank_0_0/kria_top_register_bank_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_register_bank_0_0 || ORIG_REF_NAME==kria_top_register_bank_0_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_dct_processor_0_1/kria_top_dct_processor_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_dct_processor_0_1 || ORIG_REF_NAME==kria_top_dct_processor_0_1} -quiet] -quiet

# IP: ip/COEFF_ROM/COEFF_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==COEFF_ROM || ORIG_REF_NAME==COEFF_ROM} -quiet] -quiet

# IP: ip/DCT_RAM/DCT_RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCT_RAM || ORIG_REF_NAME==DCT_RAM} -quiet] -quiet

# IP: ip/f_mult_32/f_mult_32.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_mult_32 || ORIG_REF_NAME==f_mult_32} -quiet] -quiet

# IP: ip/f_add_32/f_add_32.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_add_32 || ORIG_REF_NAME==f_add_32} -quiet] -quiet

# IP: ip/f_sub_32/f_sub_32.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_sub_32 || ORIG_REF_NAME==f_sub_32} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_auto_ds_0/kria_top_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_auto_ds_0 || ORIG_REF_NAME==kria_top_auto_ds_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_auto_pc_0/kria_top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_auto_pc_0 || ORIG_REF_NAME==kria_top_auto_pc_0} -quiet] -quiet

# XDC: d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/kria_top_ooc.xdc
