# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/CE/DAKTMT/Vivado/DATN/DATN.runs/synth_1/kria_top_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/CE/DAKTMT/Vivado/DATN/DATN.cache/wt [current_project]
set_property parent.project_path D:/CE/DAKTMT/Vivado/DATN/DATN.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.4 [current_project]
set_property ip_repo_paths d:/CE/DAKTMT/Vivado/ip_repo/register_bank_1_0 [current_project]
update_ip_catalog
set_property ip_output_repo d:/CE/DAKTMT/Vivado/DATN/DATN.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/rom_coeff_256.coe
add_files D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/rom_quant_256.coe
add_files D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/ram_test256.coe
add_files D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/cover_test.coe
add_files D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/secret_test.coe
add_files D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/dct_test.coe
add_files -quiet d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/u_add_16/u_add_16.dcp
set_property used_in_implementation false [get_files d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/u_add_16/u_add_16.dcp]
add_files -quiet d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/f_mult_32/f_mult_32.dcp
set_property used_in_implementation false [get_files d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/f_mult_32/f_mult_32.dcp]
add_files -quiet d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/f_add_32/f_add_32.dcp
set_property used_in_implementation false [get_files d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/f_add_32/f_add_32.dcp]
add_files -quiet d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/f_sub_32/f_sub_32.dcp
set_property used_in_implementation false [get_files d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/f_sub_32/f_sub_32.dcp]
read_verilog -library xil_defaultlib D:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/hdl/kria_top_wrapper.v
add_files D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/bd/kria_top/kria_top.bd
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_zynq_ultra_ps_e_0_0/kria_top_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_zynq_ultra_ps_e_0_0/kria_top_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_cdma_0_0/kria_top_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_cdma_0_0/kria_top_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_xbar_0/kria_top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_rst_ps8_0_99M_0/kria_top_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_rst_ps8_0_99M_0/kria_top_rst_ps8_0_99M_0.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_rst_ps8_0_99M_0/kria_top_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_1/bd_3ec2_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_1/bd_3ec2_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_2/bd_3ec2_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_3/bd_3ec2_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_4/bd_3ec2_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_5/bd_3ec2_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_6/bd_3ec2_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_10/bd_3ec2_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_11/bd_3ec2_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_12/bd_3ec2_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_13/bd_3ec2_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_14/bd_3ec2_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_15/bd_3ec2_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_16/bd_3ec2_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_17/bd_3ec2_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_18/bd_3ec2_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_19/bd_3ec2_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_20/bd_3ec2_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_21/bd_3ec2_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_23/bd_3ec2_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_24/bd_3ec2_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_25/bd_3ec2_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_26/bd_3ec2_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_27/bd_3ec2_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_28/bd_3ec2_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_30/bd_3ec2_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_31/bd_3ec2_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_32/bd_3ec2_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_33/bd_3ec2_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_34/bd_3ec2_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_35/bd_3ec2_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_37/bd_3ec2_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_38/bd_3ec2_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_39/bd_3ec2_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_40/bd_3ec2_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_41/bd_3ec2_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/bd_0/ip/ip_42/bd_3ec2_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_bram_ctrl_0_3/kria_top_axi_bram_ctrl_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_bram_ctrl_0_4/kria_top_axi_bram_ctrl_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_bram_ctrl_0_5/kria_top_axi_bram_ctrl_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_bram_ctrl_0_bram_2/kria_top_axi_bram_ctrl_0_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_bram_ctrl_1_bram_2/kria_top_axi_bram_ctrl_1_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_axi_bram_ctrl_2_bram_1/kria_top_axi_bram_ctrl_2_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_steganography_proces_0_3/kria_top_steganography_proces_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_dct_processor_0_1/kria_top_dct_processor_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_auto_ds_0/kria_top_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_auto_ds_0/kria_top_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_auto_ds_0/kria_top_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_auto_pc_0/kria_top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/kria_top_ooc.xdc]

read_ip -quiet D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/DCT_RAM/DCT_RAM.xci
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/DCT_RAM/DCT_RAM_ooc.xdc]

read_ip -quiet D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/COEFF_ROM/COEFF_ROM.xci
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/COEFF_ROM/COEFF_ROM_ooc.xdc]

read_ip -quiet D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/u_sub_16/u_sub_16.xci

read_ip -quiet D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/u_mult_16/u_mult_16.xci
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/u_mult_16/u_mult_16_ooc.xdc]

read_ip -quiet D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/TEST_BRAM/TEST_BRAM.xci
set_property used_in_implementation false [get_files -all d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/TEST_BRAM/TEST_BRAM_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/utils_1/imports/synth_1/kria_top_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top kria_top_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef kria_top_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file kria_top_wrapper_utilization_synth.rpt -pb kria_top_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
