# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/kria_top/kria_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top || ORIG_REF_NAME==kria_top} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_zynq_ultra_ps_e_0_0/kria_top_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kria_top_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_cdma_0_0/kria_top_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_cdma_0_0 || ORIG_REF_NAME==kria_top_axi_cdma_0_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_0_0/kria_top_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_0_1/kria_top_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_0_1 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_xbar_0/kria_top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_xbar_0 || ORIG_REF_NAME==kria_top_xbar_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_ps8_0_axi_periph_0/kria_top_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_ps8_0_axi_periph_0 || ORIG_REF_NAME==kria_top_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_rst_ps8_0_99M_0/kria_top_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_rst_ps8_0_99M_0 || ORIG_REF_NAME==kria_top_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_smc_0/kria_top_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_smc_0 || ORIG_REF_NAME==kria_top_axi_smc_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_0_bram_0/kria_top_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_1_bram_0/kria_top_axi_bram_ctrl_1_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_1_bram_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_1_0/kria_top_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_1_0 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_axi_bram_ctrl_2_bram_0/kria_top_axi_bram_ctrl_2_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_axi_bram_ctrl_2_bram_0 || ORIG_REF_NAME==kria_top_axi_bram_ctrl_2_bram_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_reg_bank_0_0/kria_top_reg_bank_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_reg_bank_0_0 || ORIG_REF_NAME==kria_top_reg_bank_0_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_dct_system_0_0/kria_top_dct_system_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_dct_system_0_0 || ORIG_REF_NAME==kria_top_dct_system_0_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_auto_ds_0/kria_top_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_auto_ds_0 || ORIG_REF_NAME==kria_top_auto_ds_0} -quiet] -quiet

# IP: bd/kria_top/ip/kria_top_auto_pc_0/kria_top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_top_auto_pc_0 || ORIG_REF_NAME==kria_top_auto_pc_0} -quiet] -quiet

# XDC: d:/CE/DAKTMT/Vivado/project_dct/project_dct.gen/sources_1/bd/kria_top/kria_top_ooc.xdc
