# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CE/DAKTMT/Vivado/project_dct/project_dct.srcs/sources_1/ip/multi_32/multi_32.xci
# IP: The module: 'multi_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/project_dct/project_dct.gen/sources_1/ip/multi_32/multi_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multi_32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/CE/DAKTMT/Vivado/project_dct/project_dct.srcs/sources_1/ip/multi_32/multi_32.xci
# IP: The module: 'multi_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/project_dct/project_dct.gen/sources_1/ip/multi_32/multi_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'multi_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
