# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/bd/kria_top/ip/kria_top_dct_processor_0_1/kria_top_dct_processor_0_1.xci
# IP: The module: 'kria_top_dct_processor_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/COEFF_ROM/COEFF_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==COEFF_ROM || ORIG_REF_NAME==COEFF_ROM} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/DCT_RAM/DCT_RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCT_RAM || ORIG_REF_NAME==DCT_RAM} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/f_mult_32/f_mult_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_mult_32 || ORIG_REF_NAME==f_mult_32} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/f_add_32/f_add_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_add_32 || ORIG_REF_NAME==f_add_32} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/f_sub_32/f_sub_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_sub_32 || ORIG_REF_NAME==f_sub_32} -quiet] -quiet

# XDC: d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_dct_processor_0_1/kria_top_dct_processor_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_top_dct_processor_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/bd/kria_top/ip/kria_top_dct_processor_0_1/kria_top_dct_processor_0_1.xci
# IP: The module: 'kria_top_dct_processor_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/COEFF_ROM/COEFF_ROM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==COEFF_ROM || ORIG_REF_NAME==COEFF_ROM} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/DCT_RAM/DCT_RAM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DCT_RAM || ORIG_REF_NAME==DCT_RAM} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/f_mult_32/f_mult_32.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_mult_32 || ORIG_REF_NAME==f_mult_32} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/f_add_32/f_add_32.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_add_32 || ORIG_REF_NAME==f_add_32} -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/f_sub_32/f_sub_32.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==f_sub_32 || ORIG_REF_NAME==f_sub_32} -quiet] -quiet

# XDC: d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/bd/kria_top/ip/kria_top_dct_processor_0_1/kria_top_dct_processor_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_top_dct_processor_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
