# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/DCT_RAM/DCT_RAM.xci
# IP: The module: 'DCT_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/DCT_RAM/DCT_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCT_RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/CE/DAKTMT/Vivado/DATN/DATN.srcs/sources_1/ip/DCT_RAM/DCT_RAM.xci
# IP: The module: 'DCT_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CE/DAKTMT/Vivado/DATN/DATN.gen/sources_1/ip/DCT_RAM/DCT_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCT_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
